### ISSUE TITLE
Increase button size? quick method or tips

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#163]
Hi, we are changing from psp X to Mollie. All is clear and works fine. 

1 thing we see on desktop the icons are very very small (almost too small)

 - does a setting exist to increase the icons?

 - if not is there a best practice? or can another user share?

Appreciate it

![image](https://user-images.githubusercontent.com/652395/75788829-13998980-5d69-11ea-825e-82e2327b6492.png)

**Comment by Frank-Magmodules** [comment]
HI @seansan ,

Thank you for opening this question. This is not a specific option. The images are [externally loaded](https://www.mollie.com/external/icons/payment-methods/klarnapaylater%402x.png) from Mollie but the image quality allows you to load them larger using CSS.

Depending on your theme you can simply load them with 50px instead of your current-theme size. A CSS code example can be something as;

```
.sp-methods label img {
    max-width:50px!important;
}
```
_Disclaimer:
This is just an example based on the default RWD theme on how to enlarge the images._

**Comment by seansan** [comment]
thx we made it this

```
/* MOLLIE */
.sp-methods label img { max-width:40px!important; }
.sp-methods dt { padding-bottom: 10px; }

```
