### ISSUE TITLE
Invoice sending

### ISSUE THREAD

**Issue by ekomurz** [mollie/Magento#179]
What might be the cause that invoices for new orders, processed through Mollie, are sent anyway ?
Even if the configuration parameter is set to NO? (And also the base setting in Magento for sending invoices is set to NO)
Invoices are sent only for orders processed through Mollie, and not for other orders (that will be paid through bank)

**Comment by Frank-Magmodules** [comment]
Hi @ekomurz ,

Strange but can you please provide the exact steps? We do need information on how to reproduce this. Otherwise please share your login details so we can take look with you through our [contact form](https://www.magmodules.eu/contact-us.html) as we do need more information like ;

- Which Magento en Mollie version are your using
- Which setting trows the _"Expected result"_ and what is the _"Actual result"_

If I have a successful payment with the "Send Invoice Email" option set to "No", the invoice is generated after successful payment but the customer is not notified, that seems to work like expected.

`Invoice #500000140 created | Customer Not Notified`

Frank

**Comment by Marvin-Magmodules** [comment]
Closing this issues due to inactivity. Please feel free to reopen if this issue still exists.
