### ISSUE TITLE
Klarna Pay Later creating double invoice

### ISSUE THREAD

**Issue by mybinaryromance** [mollie/Magento#216]
Since installing version 5.6.8 of the extension, Klarna Pay Later will create two invoices in Magento. One on autorization of the amount and another one on capturing the amount. Each invoice contains all order items and the full order total, the first one will keep the status 'pending' and the latter will be set to 'paid'.
We have the setting ' When to create the invoice?' set to 'On Authorize and set payment status Paid after shipment', which is also irritating, as the invoices are created before shipments are made.

**Comment by mybinaryromance** [comment]
![Screenshot from 2022-04-05 14-30-07](https://user-images.githubusercontent.com/8794344/161768679-c717fe70-2aaa-4ede-9dfd-77d7bead5750.png)
![Screenshot from 2022-04-05 14-30-31](https://user-images.githubusercontent.com/8794344/161768688-f7ed596f-4e3b-4876-97f1-55c5d2b41222.png)

**Comment by Frank-Magmodules** [comment]
@mybinaryromance ,

Thank you for opening this issue and sorry for my late response on this, we've tried to reproduce the issue that you describe but we can't reproduce this issue directly by following steps;

*   Invoice is being created (pending)
*   Shipment created
*   Invoice is set to paid

Can you please share the exact steps or the expected behavior with us through our [support form](https://www.magmodules.eu/support-form.html) so we can take a look with you?

**Comment by mybinaryromance** [comment]
@Frank-Magmodules ,
we can safely close this. I solved the issue by providing a detailed explanation of the magento order status workflow to my client. The error, once more, was outside the machine ;)
A little feature request on the way: you might consider disabling the 'invoice' button from an order if klarna pay later is used as a payment method and all order items have been invoiced already and  ' When to create the invoice?' is set to 'On Authorize and set payment status Paid after shipment', just to keep people from pressing it again ;)
Thank you!
