### ISSUE TITLE
Klarna Pay Later with status failed if the quantity is not an integer

### ISSUE THREAD

**Issue by barznet** [mollie/Magento#226]
CMS: Magento 1.9.4.2
Payment: Klarna Pay Later
Release: 5.7.0

LOG: 

> Canceled because an error occurred while redirecting the customer to Mollie:
> Error executing API call (422: Unprocessable Entity): Order line 5 is invalid. Total amount is off. Expected total amount to be €7.40 (1 × €7.40), got €3.70. Field: lines.5.totalAmount. Documentation: https://docs.mollie.com/overview/handling-errors"

<img width="1454" alt="#131217 : Bestellungen : Verkäufe : Magento Administration 2022-08-14 14-30-42" src="https://user-images.githubusercontent.com/8721373/184537162-12d6c3b6-63e9-411c-855d-fd135995d432.png">

**Comment by Frank-Magmodules** [comment]
Hi **@barznet ,**

Thank you for opening this issue! As the `quantity` needs to be `int` within the Mollie API, it’s not accepting fractional quantity. A workaround could be to put the unit to the item. So instead of 0.5 x 1 meter of fabric, you have 1 x 0.5 meter of fabric. 

As Magento 1 is EOL for quite some time now, we decided to not implement a workaround within the plugin for this so we will close this issue for now.

**Comment by barznet** [comment]
Thank you for your reply. Can you tell me, why in this case the payment by card and paypal works without problems? 

<img width="1173" alt="#131221 : Bestellungen : Verkäufe : Magento Administration 2022-08-16 15-55-56" src="https://user-images.githubusercontent.com/8721373/184897943-1fbfadda-1e1c-41a2-82b2-02a68d55111a.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/8721373/184898159-5bdb3dfa-a890-47d0-8c15-7087f7e4fc59.png">

**Comment by Frank-Magmodules** [comment]
Hi @barznet ,

Because this method uses the Payment API and only sends the complete amount to be captured. Some payment methods require order details (and therefore the Orders API) to function, such as Klarna Pay now, Klarna Pay later and Klarna Slice it.  
  
See: [https://docs.mollie.com/reference/v2/orders-api/overview](https://docs.mollie.com/reference/v2/orders-api/overview)
