### ISSUE TITLE
No Magento 2 support

### ISSUE THREAD

**Issue by MicroKloon** [mollie/Magento#37]
Magento 2 is officialy the only supported Magento version as of now.
When will the Mollie module work for this release?

**Comment by RicardoJ** [comment]
Hello,

Magento 1 is still supported for 3 years after the GA release of Magento 2. To answer your question:

We are currently busy developing a stable and rewritten payment module for Magento 2 since there is too much difference in coding, etc. between Magento 1 and 2.

When this new payment module for Magento 2 is available is unknown at this time.

**Comment by MicroKloon** [comment]
Supported as in major bug fixes, no new development. Ergo, Magento 2 is the way to go.

I hope you will get a working version of the Mollie connector out in a few weeks. You do know that Magento 2 comes with working Paypal and Braintree integration?

**Comment by RicardoJ** [comment]
We are aware of all these cases. Thank you again for bringing this to our attention.

We hope to have a working beta within a few weeks.

**Comment by MicroKloon** [comment]
Ok, thank you for your quick responses.

**Comment by RicardoJ** [comment]
Your welcome. If you can mail your partner details to info@mollie.com regarding Magento 2, we will add you to the list of Merchants who will be informed about our beta module, if your interested.
