### ISSUE TITLE
Recurring support

### ISSUE THREAD

**Issue by reinos** [mollie/Magento#60]
I would like to have support for the direct-debit "https://www.mollie.com/nl/payments/direct-debit" options.

**Comment by tomasmollie** [comment]
Hi Reinos,
We (Mollie) are investigating the possibility of adding recurring SEPA direct debit to our Magento plugins. Currently, due to the setup of Magento, we have not invested upon this feature. Please send me a message via tomas@mollie.com, when I have your contact details I can share you insights on the progress we will make.

**Comment by runephpp** [comment]
@tomasmollie @Marvin-Magmodules Any update on this? :)

**Comment by tomasmollie** [comment]
@runephpp could you please contact me via tomas@mollie.com . Possibly I have a solution for you on short term.

**Comment by beurze** [comment]
Any update on this? We would really like to have this feature.

**Comment by Frank-Magmodules** [comment]
Due to the upcoming end of life of Magento 1 we are not implementing this new feature in the module as we switched focus to the Magento 2 module.
