### ISSUE TITLE
Order saved even if there is an error

### ISSUE THREAD

**Issue by plpradeep** [mollie/Magento#76]
Hi,
I tried to use the module and place an order in My local machine.
As my machine i snot accessible to public, user is redirected to the cart page with the below error 
Error executing API call (request): The webhook location is invalid.

However if I check the admin sales >> Order list, I have an order created with Pending state.

Are you going to update the module to not save the order if payment is not done?

**Comment by Frank-Magmodules** [comment]
Hi, this is a requirement, see [Wiki > Troubleshooting](https://github.com/mollie/Magento/wiki/Troubleshooting): "This is because Mollie is unable to reach the Webhook of your webshop. The Webhook needs to be accessible from any location on the web. [Read More](https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem-)".

Order is saved regardless of the connection with Mollie.

**Comment by plpradeep** [comment]
But, If the payment is not success or if the connection doesn't exist, then what is the case in creating the Order?

**Comment by Frank-Magmodules** [comment]
Hi,

This is default Magento logic. Save Order -> Redirect to PSP.

**Comment by plpradeep** [comment]
Hi Frank,

Can we get the IP of the Payment gateway server so that we can allow access to only that IP?
