### ISSUE TITLE
Payment Info magento order

### ISSUE THREAD

**Issue by kuhnnl** [mollie/Magento#96]
We see that when upgrading from mollie 4.3.0 to 5.0.1 the payment info is gone from the order and changed to this 

Betaalgegevens
Api
Bestelling is geplaatst met EUR

**Comment by Marvin-Magmodules** [comment]
The payment information of orders placed before the update should only display the method title, as these dynamic methods have been replaced by static methods. This data was loaded on the fly from the API. Instead of "Api" it should display the title e.g. "iDEAL". Can you contact us through https://www.magmodules.eu/contact-us.html so we can investigate this for you?

**Comment by Marvin-Magmodules** [comment]
Method titles were saved as 'api' instead of the correct method title in v4.3.0 and lower. Made a workaround to load method title from 'mollie_methods' table in title 'api' is found. See new release [v5.0.3](https://github.com/mollie/Magento/releases/tag/v5.0.3). Closing this issue now, please feel free to reopen this issue if this problem still occurs.
